package com.group13.rag.model;

import java.util.List;

/*
  Represents the final answer generated by the RAG system.
  Corresponds to the 'Answer' entity in the Domain Model.
 */
public class Answer {
 
    private String finalText;         // The final text response to be shown to the user
    private List<Citation> citations; // List of citations supporting the answer (1..* relationship)

    public Answer(String finalText, List<Citation> citations) {
        this.finalText = finalText;
        this.citations = citations;
    }

    // Getters
    public String getFinalText() { return finalText; }
    public List<Citation> getCitations() { return citations; }

    /*
      Returns a formatted string representation of the answer and its citations.
      Useful for console output.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(finalText).append("\n");
        sb.append("Sources: "); 
        if (citations != null) {
            for (Citation c : citations) {
                sb.append("[").append(c.toString()).append("] ");
            }
        }
        return sb.toString();
    }
}