package com.group13.rag.core;

import com.group13.rag.model.Hit;
import com.group13.rag.model.KeywordIndex;
import java.util.List;

/**
 * [cite_start]Strategy Interface for the Retrieval stage [cite: 125-126].
 * This component is responsible for scanning the index to find candidate text chunks
 * that match the search terms generated by the QueryWriter.
 * * Pattern: Strategy (allows swapping between Keyword, Vector, or Hybrid retrieval).
 */
public interface Retriever {
     // Searches the inverted index for the given query terms.
    List<Hit> retrieve(List<String> queryTerms, KeywordIndex index);
}